### ISSUE TITLE
Objective sense may not be reflected in NodeBipartite

### ISSUE THREAD

**Issue by AntoinePrv** [ds4dm/ecole#146]
## Describe the bug
The objective coefficient is collected without checking for whether the problem is a maximization or minimization.
For columns, is the LP always assumed to be a minimization? This might not be the same policy as for variables.
If not, we need to manually flip the sign.

## Expected behavior
We should be able to recover the problem without losing information.

## Additional context
 - [ ] Check with SCIP developers whether the sign needs to be manually flipped.

**Comment by dchetelat** [comment]
I made verifications. Things look ok with the NodeBipartite observation: the objective coefficient of a set cover variable (minimization) is
```python
> obs.column_features[0, :]
array([0.00817096, 1.        , 0.        , 0.        , 0.        ,
       1.        , 1.        , 0.        , 0.98408131, 0.98408131,
       0.        , 0.        , 0.        , 1.        , 1.        ,
       0.        , 1.        , 0.        , 0.        ])
```
that is `0.00817096 > 0`, and the objective coefficient of a combinatorial auction instance (maximization) is
```python
> obs.column_features[0, :]
array([-2.59638592e-02,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  1.00000000e+00,  3.66044879e-02,
       -0.00000000e+00, -0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        7.75510204e-01,  0.00000000e+00,  3.25824289e-08,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00])
```
that is `-2.59638592e-02 < 0`. So the problem is always normalized to a minimization problem.

With the new MilpBipartite, everything seems also: the objective coefficient of a set cover variable (minimization) is 
```python
> obs.variable_features[0, :]
array([72.,  1.,  0.,  0.,  0.,  1.,  1., -0.,  1.])
```
that is `72 > 0`, and the objective coefficient of a combinatorial auction variable (maximization) is
```python
> obs.variable_features[0, :]
array([-171.58883872,    1.        ,    0.        ,    0.        ,
          0.        ,    1.        ,    1.        ,   -0.        ,
          1.        ])
```
i.e.e `-171.58883872 < 0`. That is, with the sign convention, we always have a minimization problem.

So everything looks ok! I think we can close the issue.

**Comment by AntoinePrv** [comment]
Ha right, because there are two functions `SCIPcolGetObj` and `SCIPvarGetObj`.
So this means that `SCIPcolGetObj(col)` and `SCIPvarGetObj(SCIPcolGetVar(col))` might have a sign difference!

**Comment by dchetelat** [comment]
Yeah must have been!
