### ISSUE TITLE
Can StrongBranch be used for nonlinear integer optimization?

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [ds4dm/ecole#276]
### Discussed in https://github.com/ds4dm/ecole/discussions/275

<div type='discussions-op-text'>

<sup>Originally posted by **cloud-waiting-for-wind** November  5, 2021</sup>
Can StrongBranch be used for nonlinear integer optimization?
I try to use   ecole.observation.StrongBranchingScores()  on a  nonlinear integer optimization instance,  however,  all entries in the score are 1e-12.  

I'm not sure if  I made a code mistake or ecole.observation.StrongBranchingScores()  doesn't work on nonlinear integer optimization?</div>

**Comment by gasse** [comment]
Hi @cloud-waiting-for-wind ,

In general all of Ecole (environments, observation functions etc.) is designed with mixed-integer linear optimization in mind. Things might work with non-linear optimization as well, although I'm not sure what the expected behaviour should be. Regarding strong branching scores, I am not sure if those even have a standard definition for nonlinear optimization. Maybe this is something you should ask to the SCIP developers directly.

Best,
Maxime
