### ISSUE TITLE
Observation function for configuration environment

### ISSUE THREAD

**Issue by dchetelat** [ds4dm/ecole#95]
Right now the tutorial on the configuration environment assumes that no info about instances are available (classic bandit problem). However, we could imagine that some information, say at least A, b, c, is available to make a decision as to how to tune the solver (contextual bandit problem). However, none of the currently supported observation functions (flat-Khalil and bipartite-Gasse style) make sense for this context, since they carry additional info that is unavailable until at least the root node LP is solved. Thus it would make sense to prepare at least one reasonable observation function for configuration.

The simplest option in my book would be a bipartite graph representation containing A, b, c. This would be a stripped version of the branching bipartite observation function, but already something interesting to play with (plus, it would mean offering a deep GNN bandits problem, something really fun!)

**Comment by AntoinePrv** [comment]
I have isolated the contraint matrix of `NodeBipartite` into a separate class (that is being reused in `NodeBipartite`).
However, I'm not sure this can be used here, because it is defined in term of rows/cols and not cons/vars.
This could still be useful to configure at the root node.
Otherwise, I don't know if it would make sense to index `NodeBipartite` in term of cons/vars.
